### ISSUE TITLE
Upgrade to GHC 9.2

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#101]
**Problem:**
 - Atlas is using GHC 8.10 at the moment, which is not compatible with Plutarch.

**Solution:**
 - Upgrade to GHC 9.2.

**Comment by 4TT1L4** [comment]
We need to double-check if the code base is really compatible and nothing is going to break.

@sourabhxyz Could you please confirm?

**Comment by sourabhxyz** [comment]
@4TT1L4 I am a bit confused, there is no PR yet for this issue.

**Comment by sourabhxyz** [comment]
IIUC, even the latest version of `cardano-api` (which is an essential dependency of framework) is using an older version of `base` (https://github.com/input-output-hk/cardano-node/blob/1.35.7/cardano-api/cardano-api.cabal#L14) blocking 9.2 upgrade at this point.

**Comment by 4TT1L4** [comment]
Please create a new issue, if you wish to upgrade the compiler version used by the CI.

It is also possible to have different builds with different GHC versions, like here:

https://github.com/input-output-hk/cardano-node/blob/2c9190f7813774f6a3dc13fb15e1ef20fc9786b6/.github/workflows/haskell-linux.yml#L28
