### ISSUE TITLE
Update Node/Api to latest

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/atlas#106]
Currently we are in 1.35.4

**Comment by 4TT1L4** [comment]
After addressing this, the compilations warnings could be fixed:
 - https://github.com/geniusyield/atlas/issues/121

**Comment by sourabhxyz** [comment]
It turns out that, at this point, there is a conflict b/w two of our dependencies here, namely, `cardano-wallet` & `cardano-node` where `cardano-node` wants version of `network-mux` to be [`^>= 0.2`](https://github.com/input-output-hk/cardano-node/blob/1.35.7/cardano-node/cardano-node.cabal#L164) and `cardano-wallet` wants it to be `^>= 0.3` (coming from the [`ouroboros-network-api`](https://github.com/input-output-hk/cardano-wallet/blob/v2023-04-14/lib/wallet/cardano-wallet.cabal#L819), whose even the earliest release (`0.1.0.0`) requires `network-mux` to be [`^>= 0.3`](https://github.com/input-output-hk/ouroboros-network/blob/ff2d04567b6c19b3a52207809ebd5dcf65528fae/ouroboros-network-api/ouroboros-network-api.cabal#L67)).

**Comment by TotallyNotChase** [comment]
It'd be better to focus on updating to node `^>= 8.1`

But yeah, updating to a conforming cardano-wallet will be hard. There is currently no `cardano-wallet` version that supports anything above 1.35.4 - which is really problematic and IOG ought to do something about it

**Comment by sourabhxyz** [comment]
@TotallyNotChase Yes, I planned to update to version `8.0.0` (and now `8.1.1`) and had raised this issue in `cardano-wallet` repository https://github.com/input-output-hk/cardano-wallet/issues/3945.

Having `cardano-wallet` as a dependency limits us and I am looking into if we can not depend on it.

**Comment by sourabhxyz** [comment]
Closing in favor of #166.
