### ISSUE TITLE
Atlas package name is taken on Hackage

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#128]
**Problem:**
 - The atlas package name is already taken on Hackage, so we cannot publish the package with this name.

**Solution:**
 - Change the package name to a name that is still available on Hackage.
 
 **Resources:**
 - The atlas package on Hackage: https://hackage.haskell.org/package/atlas (already taken!)

**Comment by FilipBl4gojevic** [comment]
atlas-cardano will be the name

**Comment by 4TT1L4** [comment]
> atlas-cardano will be the name

@sourabhxyz please update the name accordingly, so we could publish version 0.3.0 on Hackage as well as soon as it is available. 

Thank you.
