### ISSUE TITLE
Improve Coin selection

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/atlas#143]
To study:
* Relationship between datum & reference script for cardano wallet's coin selection algorithm: https://github.com/geniusyield/atlas/blob/87fcce0c6eb9ee261f7f71491e2c7dd7fe7f1413/src/GeniusYield/Transaction/CoinSelection.hs#L194-L201
  *  Currently we fix for it later: https://github.com/geniusyield/atlas/blob/87fcce0c6eb9ee261f7f71491e2c7dd7fe7f1413/src/GeniusYield/Transaction/CoinSelection.hs#L175 but as mentioned here https://github.com/geniusyield/atlas/blob/87fcce0c6eb9ee261f7f71491e2c7dd7fe7f1413/src/GeniusYield/Transaction/CoinSelection.hs#L60, we can make `Address` type here to uniquely identify tx output in our function to compute for minimum ada.
* Study the breaking changes in `cardano-wallet` and how the new feature of it providing the collateral inputs to be used in transaction can be useful.  
* Is `UnableToConstructChange` thrown by `cardano-wallet` imply that it won't be possible build a valid tx even with change of strategy? In such a case we can communicate to user that indeed there are insufficient funds.
* The `useInline` variable seems redundant as it is always set to `True`.
* Fix some other TODO & comments present in files related to coin selection.

**Comment by MarvinBertin** [comment]
@TotallyNotChase do you think you could help with this ticket?

**Comment by TotallyNotChase** [comment]
I did have an idea for this in mind but never had the time to implement it. I mostly left the details for it in those comments (basically making the `Address` associated type uniquely identify a utxo). I'm definitely down to help out by discussing/answering questions around the design I initially envisioned - though it'd probably take me too long to actually implement it myself right now - too busy with other projects :(

**Comment by sourabhxyz** [comment]
Changes done for this are mentioned in this PR: https://github.com/geniusyield/atlas/pull/163#issue-1771630057.
