### ISSUE TITLE
Add a way to add transaction metadata

### ISSUE THREAD

**Issue by eddiemundo** [geniusyield/atlas#144]
A field in GYSkeleton maybe?

**Comment by sourabhxyz** [comment]
Hi @eddiemundo, thanks for bringing up this issue! This is definitely possible, I'll add it to my todo list.

**Comment by sourabhxyz** [comment]
@eddiemundo I notice that you have a fork implementing for it, would you like to upstream it?

**Comment by ajuggler** [comment]
@sourabhxyz  With [latest commit](https://github.com/geniusyield/atlas/compare/main...144-add-a-way-to-add-transaction-metadata), I am able to write Tx metadata using [this code](https://gist.github.com/ajuggler/fb53336437cc2543488bece1ddbef91e).

**Comment by sourabhxyz** [comment]
Completed #293, #285.
