### ISSUE TITLE
EraHistory | Can we ensure runtime, that Interpreter is still a newtype to Summary?

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#20]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/src/GeniusYield/CardanoApi/EraHistory.hs#L22

**Comment by sourabhxyz** [comment]
Closing as I don't think it's possible to ensure for this at runtime. We just need to be careful with use of `unsafeCoerce`.
