### ISSUE TITLE
CoinSelection | This currently doesn't care about datum/ref script, even though they affect costs

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#24]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/src/GeniusYield/Transaction/CoinSelection.hs#L194

**Comment by sourabhxyz** [comment]
It need not be provided for as this function is ran only for generated change outputs which do not have datum & ref script.
