### ISSUE TITLE
Gift | later these tests fail due NonOutputSupplimentaryDatums. The reason is wrong grabGifts. We should use GyTxInDatum True there for datums

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#26]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/src/GeniusYield/Test/Privnet/Examples/Gift.hs#L409

**Comment by sourabhxyz** [comment]
Already resolved for.
