### ISSUE TITLE
rejecting: atlas-cardano-0.4.0 (conflict: requires GHC2021 which is not supported)

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas#267]
**Describe the bug**
I'm trying to compile my project which I started developing with the atlas release version 0.2.0. I'm currently trying to bump it 0.4.0, but I get the following error message:

```
HEAD is now at 887633f Merge pull request #262 from geniusyield/fix-semantic-version-in-the-release-workflow
Warning: The package list for 'hackage.haskell.org' is 18 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: The package list for 'cardano-haskell-packages' is 18 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: atlas-cardano (user goal)
[__0] rejecting: atlas-cardano-0.4.0 (conflict: requires GHC2021 which is not
supported)
[__0] fail (backjumping, conflict set: atlas-cardano)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: atlas-cardano
```

The `default-language` of my project's cabal file is `Haskell2010`. I wonder if there is any way to make it work.

**To Reproduce**
1. Set `default-language` of project (in <project>.cabal file) to `Haskell2010`
2. Try compiling the project using atlas' latest release (0.4.0) 

**Expected behavior**
A success compilation.

**Station (please complete the following information):**
 - OS: nix on macos (M2 Max)
 - Version 2.18.1

**Additional context**

**Comment by sourabhxyz** [comment]
Hi @Fiftyw3bs, Atlas now requires GHC version to be 9.2.8. You may look at our CI file https://github.com/geniusyield/atlas/blob/main/.github/workflows/haskell.yml, which sets up the required environment on Ubuntu VM.

**Comment by sourabhxyz** [comment]
Also it should be fine if your project is on `Haskell2010` but dependencies (such as Atlas) is on `GHC2021`.

**Comment by Fiftyw3bs** [comment]
@sourabhxyz Thank you very much for the prompt response.

I unfortunately spent the whole of yesterday trying to bump ghc from 8.10.7 to 9.2.8 to no avail. I could not resolve the dependencies
