### ISSUE TITLE
GHC 9.6 support

### ISSUE THREAD

**Issue by eddiemundo** [geniusyield/atlas#275]
It would be nice, and I think it's possible dependencies-wise.

**Comment by sourabhxyz** [comment]
Yup, it is certainly possible and something that we as well want so as to try out wasm backend. The only thing which is perhaps blocking is `cardano-wallet` dependency as it is usually the late one to get updated.

**Comment by euonymos** [comment]
I got all core modules compiled. Some notes:
* several places need attention, will get back to them
* support for PSM is dropped

**Comment by euonymos** [comment]
Closed by #313.
