### ISSUE TITLE
"CekError An error has occurred" while running unit test

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas#281]
**Describe the bug**
I'm trying to execute my test, but getting the follow:

```
Generic fail: [ValidationFailure (ValidationFailedV2 (CekError An error has occurred:  User error:
               The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.) [] PlutusDebug Omitted)]
      Slot 10: Generic fail: GenericFail "[ValidationFailure (ValidationFailedV2 (CekError An error has occurred:  User error:\nThe machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.) [] PlutusDebug Omitted)]"
```

I'm finding it difficult figuring out where the problem may lie.

**To Reproduce**

My validator has the following modules imported:

```haskell
import PlutusLedgerApi.V2 qualified as PlutusV2
import PlutusLedgerApi.V1.Value as Value
import PlutusLedgerApi.V2.Tx                 as PlutusV2 (isPubKeyOut)
import PlutusTx
import PlutusTx.Prelude
import Prelude (Show, Read, Eq)
import Cardano.Api hiding (ScriptHash)
import GHC.Generics (Generic)
import qualified PlutusTx.Maybe as PMaybe
import qualified PlutusTx.AssocMap as PMap
import qualified PlutusTx.Ratio as PRatio
import PlutusLedgerApi.V2.Contexts (ownCurrencySymbol)
import PlutusLedgerApi.V1.Address as PlutusV2 (pubKeyHashAddress, toPubKeyHash )
```

I'm using atlas `v0.4.0`

**Expected behavior**
Successful execution of test.

**Station (please complete the following information):**
 - OS: Nix on Macbook Pro M2 Max
 - Version 2.19.2

**Comment by sourabhxyz** [comment]
This simply means that one of your validator condition failed, say you are patten matching on `Just ...` but value is actually `Nothing`. You can add traced to your script to know which condition/assumption actually failed.

**Comment by sourabhxyz** [comment]
I am closing as I believe it's not an unexpected behaviour, feel free to reopen o/w.

**Comment by Fiftyw3bs** [comment]
Thanks @sourabhxyz  for the response. You are right about the source of the issue.
