### ISSUE TITLE
How to get a validator's own hash

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas#286]
**Describe the bug**
This may not be the appropriate place for this question. But it seems `ownHash` of `PlutusLedgerApi.V1.Contexts` is missing in`plutus-ledge-api v1.6.0.` used in `atlas v0.4.0`. How do folks - using atlas - get a Validator's own hash?

**To Reproduce**
Make use of atlas `v.0.4.0, try calling ownHash from within a validator.

**Expected behavior**
Every function provided by `plutus-ledger-api` should be available.

**Station (please complete the following information):**
 - OS: Nix on Mac OS
 - Version 2.19.2

**Comment by sourabhxyz** [comment]
You want to get it onchain?

**Comment by Fiftyw3bs** [comment]
Yes

**Comment by sourabhxyz** [comment]
You can find your own input and take payment credential from address field.

**Comment by sourabhxyz** [comment]
Please re-open if relevant.
