### ISSUE TITLE
CardanoDbSync | add testnet and mainnets

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#35]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/src/GeniusYield/Providers/CardanoDbSync.hs#L420

**Comment by sourabhxyz** [comment]
DB-Sync is removed in favour of Kupo, which has support for mainnet, preprod, preview and our private network.
