### ISSUE TITLE
CoinSelection | Should we use different recipient addresses for each output?

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#36]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/tests/GeniusYield/Test/CoinSelection.hs#L390

**Comment by sourabhxyz** [comment]
This comment is belonging to a test file and does not affect library code, likely written at whim of author. I personally don't think it's relevant to track for it.
