### ISSUE TITLE
Testing with multisig

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas#366]
As the title suggests, how does one test a scenario where a script utxo has to be signed by two separate wallets?

**Comment by sourabhxyz** [comment]
Hey @Fiftyw3bs, the question is not entirely clear. Can you check [this](https://github.com/geniusyield/atlas/blob/main/tests-privnet/GeniusYield/Test/Privnet/SimpleScripts.hs) test code & see if it solves your issue? Shared test involves requiring multiple signatories.

**Comment by sourabhxyz** [comment]
Please reopen if still relevant.
