### ISSUE TITLE
Constructing offchain code for transaction with multisig N of M signers

### ISSUE THREAD

**Issue by Fiftyw3bs** [geniusyield/atlas#374]
My validator allows N or M signers to sign a transaction, but I'm perplexed about how to construct the offchain code to accomodate that fact.

Currency, it's implemented so: `foldMap mustBeSignedBy creators`, but I get the error: `ApplyTxError (ConwayUtxowFailure (MissingVKeyWitnessesUTXOW (fromList [KeyHash {unKeyHash = ...`, since all M signers are included but only N or M have signed the transaction.

Is there a solution or workaround for this? It'd be greatly appreciated.

**Comment by sourabhxyz** [comment]
Hi @Fiftyw3bs! This is one nice advantage of using Simple Scripts compared to Plutus Scripts! We have also faced this issue in past and I don't think there is a way around. Essentially, in your off-chain code you must demand signatures from only those that you know would sign your built tx.
To be noted that Atlas also supports Simple scripts and we have it's documentation [here](https://atlas-app.io/additional-features/simple-scripts). I am not sure but if you can plug simple script inside withdraw zero trick then you can get best of both worlds.
Also, in our GeniusYield discord we now have channel dedicated to Atlas, you can ping me there as well.
Recently, we are also trying to keep atlas documentation up to date with latest atlas release, and as of now it tracks latest major release.
