### ISSUE TITLE
 Add `Control.Monad.IO.Class.MonadIO` instances for monads in `GeniusYield.TxBuilder.IO` (GYTxGameMonadIO, GYTxMonadIO, etc.)

### ISSUE THREAD

**Issue by jaredponn** [geniusyield/atlas#377]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'd like to do arbitrary IO in the monads provided in https://haddock.atlas-app.io/GeniusYield-TxBuilder-IO.html (e.g. `GYTxMonadIO`) and since these aren't instances of `MonadIO`(<https://hackage.haskell.org/package/base-4.20.0.0/candidate/docs/Control-Monad-IO-Class.html>) we can't do arbitrary IO in these monads.

**Describe the solution you'd like**
I would love it if `MonadIO` instances were provided for the aforementioned monads. Those monads run in the IO monad anyways, so I don't think this is harmful.

**Describe alternatives you've considered**
Since running the aforementioned monads runs in IO in the end anyways, one could do something like
```haskell
do
  blah <- runGYTxMonadIO .... <some computation>
  blargh <- randomIOAction
  runGYTxMonadIO ... <some other computation>
```
to achieve the same effect as doing something like the following (assuming the MonadIO instances are implemented)
```haskell
do
  runGYTxMonadIO .... do 
   blah <- <some computation>
   blargh <- liftIO $ randomIOAction
   <some other computation>
```

**Additional context**
Not sure if more context is needed, but would be happy to provide any context required :)

**Comment by sourabhxyz** [comment]
Does following solve your use case? We provide more information in [this](https://github.com/geniusyield/atlas/releases/tag/v0.6.0) release note.
```hs
import           GeniusYield.Unsafe                    (unsafeIOToQueryMonad, unsafeIOToTxBuilderMonad)

instance MonadIO GYTxQueryMonadIO where
    liftIO = unsafeIOToQueryMonad

instance MonadIO GYTxBuilderMonadIO where
    liftIO = unsafeIOToTxBuilderMonad
```

**Comment by jaredponn** [comment]
Oh thank you! That does solve my use case! Merry Christmas / happy holidays btw ;)

**Comment by sourabhxyz** [comment]
Glad to hear that, and merry Christmas / holidays to you as well mate!
