### ISSUE TITLE
Maestro Provider | protocolParamMinUTxOValue should be returned by Maestro?

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#40]
https://github.com/geniusyield/atlas/blob/0cf1d0977a4c2b1c837f4339f13c20aa7a4133b6/src/GeniusYield/Providers/Maestro.hs#L565

**Comment by sourabhxyz** [comment]
Nope as it got deprecated in Alonzo hardfork.

**Comment by sourabhxyz** [comment]
Currently integrating Maestro-SDK to Atlas. Previous code for Maestro provider would thus get deleted (along with mention of comments for these issues).
