### ISSUE TITLE
Release and publish to Hackage (v0.3.0)

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#63]
**TODO:**
 - The recently released v0.2.0 of Atlas must be still released to Hackage.

**Blocked by:**
 - https://github.com/geniusyield/atlas/issues/128

**Comment by 4TT1L4** [comment]
Unfortunately the "Atlas" Package name is already taken on Hackage:
https://hackage.haskell.org/package/atlas

We need to upload the package with a different name, that is still available.

**Comment by sourabhxyz** [comment]
As discussed in our internal communications, we would not be able to release to Hackage as we depend upon dependencies which are not on Hackage.

In future, we can publish to [CHaP](https://github.com/input-output-hk/cardano-haskell-packages) once we get rid of hacks in our `cabal.project` file.
