### ISSUE TITLE
Pagination support for multi return endpoints

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/atlas#65]
The framework should start to require and take advantage of pagination in some of its Core provider functions. For example, fetching all UTxOs at an address should be a paginated operation ideally.

This would greatly help the orderbot framework. But in reality, this is a fundamental improvement that is crucial for HTTP based providers (blockfrost, maestro etc.).

**Comment by sourabhxyz** [comment]
@4TT1L4 Sorry, I didn't notice it earlier. Yes it is no longer relevant.
