### ISSUE TITLE
place-vesting tx fails with error BuildTxBalancingError

### ISSUE THREAD

**Issue by asnakep** [geniusyield/atlas#86]
**Describe the bug**
place-vesting tx fails with error BuildTxBalancingError

**To Reproduce**

-- clone atlas repo
-- clone atlas-examples repo

from atlas repo main branch:
-- run nix develop 
-- run cabal update and cabal build
-- run "cabal run" to check tests result

-- cd into atlas-example/vesting (without exiting from nix develop shell)
-- run cabal update and cabal build

-- create two addresses with cardano-cli and fund them, the receiver must have at least 5 ada for collateral
-- get a preprod key from www.gomaestro.org and add it to config file

**Error details:**
[~/atlas-examples/vesting]$ cabal run place-vesting -- config.json sender.skey $(cat recipient.addr) 2023-04-05T10:20:00Z 1255000000
Up to date
configuration file: config.json
sender skey file: sender.skey
beneficiary: db364a1b46509b5e025f701419abfcdd1f79f282ac0cd8e9577e3810
deadline: 2023-04-05T10:20:00Z
amount: 1255000000
vesting address: addr_test1wpswl090fx3rnk88xs20r5aeqcdycu08px7gt6u2eqhthxgkdkqes
sender collateral: d951ef0f8c770f66b4a7066a4c127f1f249bdb2d91428d009155e3c4e754bcc0#0
[2023-04-05 11:47:51][GeniusYield.place-vesting][Error][hostname][PID 67347][ThreadId 4][atlas-0.1.0.0-55679165f16a097540c1ef0ff3647101cc7bb717850fba7e18d621feaeca75f9:GeniusYield.Providers.Katip src/GeniusYield/Providers/Katip.hs:22:34] ERROR: BuildTxBalancingError (BalancingErrorInsufficientFunds (valueFromList [(GYLovelace,1256000000)]))
place-vesting: BuildTxBalancingError (BalancingErrorInsufficientFunds (valueFromList [(GYLovelace,1256000000)]))

**Expected behavior**
place-vesting tx must be successful.

**Screenshots**
place-vesting.png
![place-vesting](https://user-images.githubusercontent.com/53517506/230072071-140b0064-4272-4f29-af25-0a3a876ced57.png)

**Station (please complete the following information):**
NixOs 22.11.3535.799d153e4f3 (Raccoon)

**Comment by asnakep** [comment]
each time I add an amount I get the error message with that amount +1 ada

**Comment by sourabhxyz** [comment]
A) Does your wallet have enough funds?
B) Your wallet would need at least two UTxOs as one is reserved for collateral which must have amount >= 5 ada (see `Utils.hs` `offchain/Vesting`).

**Comment by sourabhxyz** [comment]
haddock for `getCollateral'` function called in `Utils.hs`: https://haddock.atlas-app.io/GeniusYield-TxBuilder.html#v:getCollateral-39-

**Comment by asnakep** [comment]
Thanks you so much, I sent 5ada to sender vest address to create another utxo and place-vest went fine
tested ok retrieve too
kind regards,
Manuel
